### ISSUE TITLE
Consider in-line descriptions as a technique

### ISSUE THREAD

**Issue by jasonjgw** [daisy/aria-details#1]
As discussed at the DIAGRAM Standards meeting several weeks ago, consider the following as a possible technique. The markup is outlined below.

```html
<figure>
<img src="diagram.jpg" alt="brief summary">
<div class="offscreen" role="region" aria-label="Description">
[Detailed description appears here.]
</div>
</figure>
```

A figcaption element could optionally be included also.

(edited by Romain on Wed 30, 14:27 UTC to add some formatting around the markup sample)

**Comment by jasonjgw** [comment]
If desired, you could also add `aria-details="desc"` to the `IMG` element and `id="desc"` to the `DIV` element.

I doubt this would help the user much, but I wouldn't expect it to be harmful either, even under implementations that don't support ARIA 1.1 yet.

**Comment by danielweck** [comment]
Added:
https://github.com/daisy/aria-details/blob/master/test9.html

**Comment by danielweck** [comment]
While creating an EPUB package for all the demos, I realized that the figure div must be included inside the figcaption in order for the HTML document to validate (tested with EPUB-Check). So I moved the offscreen div inside the figcation, and the figcaption is therefore not optional anymore.
